# Generated by Django 5.2.12 on 2026-03-09 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ACTIVAR', 'Activar'), ('INACTIVAR', 'Inactivar'), ('PUBLICAR', 'Publicar')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID objeto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cambios', models.JSONField(blank=True, default=dict, verbose_name='Cambios')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_cambios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Control de Cambio',
                'verbose_name_plural': 'Control de Cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
