# Generated by Django 5.2.12 on 2026-03-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacion',
            options={'verbose_name': 'Anotación', 'verbose_name_plural': 'Anotaciones'},
        ),
    ]
